### ISSUE TITLE
Docs-page shows 404

### ISSUE THREAD

**Issue by fratzinger** [DaddyWarbucks/feathers-fletching#18]
https://daddywarbucks.github.io/feathers-fletching/ shows 404
![image](https://user-images.githubusercontent.com/22286818/115388274-faa59f00-a1db-11eb-8547-7f30fb19e073.png)

Very sad! 😢 If I can somehow help to fix this, let me know!
Thanks for this great library, btw! ❤️

**Comment by DaddyWarbucks** [comment]
Fixed! Thanks! I am not sure what happened there? I redeployed the docs and everything is back up.

**Comment by fratzinger** [comment]
perfect. Thanks for the quick response!
