### ISSUE TITLE
Create withParam and withoutParam hooks. 

### ISSUE THREAD

**Issue by RubyRubenstahl** [DaddyWarbucks/feathers-fletching#29]
I have a use-case where I need to attach some data to `context.params` and realized that the same concept of withData, withQuery, etc could easily apply to the params object. 

I'd be willing to take on adding it in.

**Comment by DaddyWarbucks** [comment]
This sounds like a great idea. I have thought about it as well, so I am glad you also see some value in it. 
I would appreciate you adding it. It should be almost identical to `withData`. Let me know if you have any questions.

I have been meaning to make some updates as well, so this will give me an opportunity to get in there and cleanup some other stuff.

**Comment by RubyRubenstahl** [comment]
@DaddyWarbucks Yeah, I'd looked at the code for getData and it looks like it should be a fairly easy adaptation.
