### ISSUE TITLE
rate-limiter-flexible is mistakenly in devDependencies?

### ISSUE THREAD

**Issue by Artaud** [DaddyWarbucks/feathers-fletching#55]
Hi Beau!
I'm trying to build my project that newly undergone the migration to Dove and it doesn't build due to feathers-fletching, complaining that it cannot find the `rate-limiter-flexible` package, which is being imported in the rateLimit hook.

That lib is in package.json, but listed under devDependencies. Guess it should be under dependencies?

Thanks for your great work around feathers!

**Comment by DaddyWarbucks** [comment]
That is odd. `rate-limiter-flexible` is a peer dependency because you have to supply your own `rateLimiter` argument. Are you sure you have `rate-limiter-flexible` installed as a dependency in your own project?

**Comment by Artaud** [comment]
Well I have now :) the thing is that I was not using the `rateLimit` hook at all, just other hooks, but it still wouldn't let me build my project. Am I doing something wrong?

**Comment by DaddyWarbucks** [comment]
I don't know...I hate TS...
But, I published `2.0.2` that moves it to dependencies. Let me know if that doesn't work.

**Comment by Artaud** [comment]
I tried hard not to let you know since it works :) but couldn't hold myself. 

Big thanks for the fix and for the unbelievable response time.
